### ISSUE TITLE
(BUG?) scp966 increases weight instead of decreasing stamina

### ISSUE THREAD

**Issue by TheComicRelief** [FelixAllard/SCP966LC#1]
I don't know if this is intentional but he doesn't seem to decrease stamina at all but instead increase weight. Probably not because the game gets unplayable once the weight goes past 300+ lbs.

**Comment by FelixAllard** [comment]
Hello there!
Thank you for reporting this problem with me!. So in short, at first we wanted to affect stamina, but after reflection, we decided to affect weight. But you should not get more than 52lbs from this monster, so that is where the bug is. I'll be fixing this in the next patch!

**Comment by FelixAllard** [comment]
I fixed it!
